#!/bin/bash

if [ $(id -u) != 0 ]; then
    echo " Script must be run as root"
    exit
fi

echo " Building the module"
make -j$(nproc)

# Set udev rule for tx power
echo -e "\n Adding udev rule for 8812au device"
cp rtl8812-txpower.rules /etc/udev/rules.d/rtl8812-txpower.rules

echo -e "\n Installing the module..."
make install
